### ISSUE TITLE
Replace assets once we have the final logo.

### ISSUE THREAD

**Issue by willjgriff** [1Hive/celeste-swarm#12]
Activity panel logo icon, welcome modal and favicon

**Comment by fioreb** [comment]
![iso.svg](https://images.zenhubusercontent.com/5e5e8c1fc9cab6016da3157e/55445b89-2744-461d-8767-5e82363f1a54)

![celeste logo icon inactive.svg](https://images.zenhubusercontent.com/5e5e8c1fc9cab6016da3157e/ab4226fc-2e6d-4f40-b66b-dad6c4526df2)

![celeste-logo.svg](https://images.zenhubusercontent.com/5e5e8c1fc9cab6016da3157e/1c177403-98d9-46fc-a14e-8487ad381c0b)

![question list small.jpg](https://images.zenhubusercontent.com/5e5e8c1fc9cab6016da3157e/b6ea58de-0548-418f-b309-8b09950b1d87)

![question list large.jpg](https://images.zenhubusercontent.com/5e5e8c1fc9cab6016da3157e/c7423c5e-2574-4f31-84dc-9b5958a617d6)

**Comment by fioreb** [comment]
[https://app.zenhub.com/files/312037012/147023d1-29a1-42ff-b7cc-78731dadf70b/download](https://app.zenhub.com/files/312037012/147023d1-29a1-42ff-b7cc-78731dadf70b/download)

There you can find the assets that were missing.
