### ISSUE TITLE
Deploy celeste backend

### ISSUE THREAD

**Issue by willjgriff** [1Hive/celeste-swarm#2]
We need to fork and deploy the court backend and connect it to our deployment of Celeste.

https://github.com/aragonone/court-backend

Some of the features likely in the current repo that are required include:
- An email service notifying keepers (/jurors) that they have a question to answer.
- Automatically calling the draft() and settle() function on the DisputeManager contract when disputes are created and finalised respectively. Presumably the service as it is monitors for events and call these functions as soon as it needs too.
- There may also be a feature to call the heartbeat() function somewhere, curious for any details regarding this.

There may be other features included but we must ensure that at the least the above services are provided.

Whatever account calls the contract functions draft() and settle() will be rewarded some amount of HNY. All HNY earned by the service should be sent to the common pool periodically. We will manually top up the service with xDAI to call the functions. In the future we may make the service convert the HNY to xDAI but for now we'll top it up manually (unless it seems straight forward to implement).

There is also feature to auto reveal votes which needs to be disabled. When keepers/jurors vote it is using a commit-reveal process. They will have 2 days to vote on an issue using a hash of their vote, then 2 days to reveal their vote. These services provide an auto-reveal option so users don't have to return to reveal their vote, which we want to disable.

**EDIT: The below additional function is no longer needed thanks to @onbjerg implementing it.**

***

We will also need to add a new contract function which is to be called once an hour. This function will update the price oracle used for updating the courts fee prices. The courts fee prices are valued in HNY so they periodically need updating to be equal to a stable value. The code for oracle can be found here: https://github.com/1Hive/uniswap-v2-periphery/blob/master/contracts/examples/IncentivisedSlidingWindowOracle.sol and the function that requires calling is `update()`. When ready I can get the ABI.

xDAI oracle address: `0x62f0362f801E1486f1087EA6D4048390Eb93cf48`
xDAI update call: `update("0x71850b7e9ee3f13ab46d67167341e4bdc905eef9", "0xe91d153e0b41518a2ce8dd3d7944fa863463a97d")`

Rinkeby oracle address: `0xEa6d3F03d3A7bFa02cC7Ab9AA1df5cDC515b3627`
Rinkeby update call: `update("0x6D769dF557BF453ff63e1B985Fb575C7ffEE13b6", "0x4ABE2999dea3332d2c798e92b81A0c1df1A6cc5f")`

**Comment by crisog** [comment]
The backend was deployed on December 17th, now adding it to the dashboard for reference.

http://celeste-app-rinkeby.1hive.org/
http://celeste-monitoring-rinkeby.1hive.org/
http://celeste-server-rinkeby.1hive.org/

There were a few errors that showed up after I changed the court address to the latest deployment on Rinkeby:
`0xdA4d0E51dD16D0b2A0baA81aE48D990926958B28`

**Comment by crisog** [comment]
I will add the mentioned additional services as soon as they are deployed.
